site_name: Omeka S Developer Documentation
theme:
    name: 'readthedocs'
    include_homepage_in_sidebar: false
    navigation_depth: 3
repo_url: 'http://github.com/omeka/omeka-s-developer'
extra_css:
    - css/extra.css
markdown_extensions:
    - toc:
        permalink: ïƒ

