site_name: Omeka S Developer Documentation
theme:
    name: 'material'
    include_homepage_in_sidebar: false
    navigation_depth: 3
    logo: assets/omeka-logo.png
    font:
        text: Lato
repo_url: 'http://github.com/omeka/omeka-s-developer'
extra_css:
    - css/extra.css
    - css/iconfonts.css
markdown_extensions:
    - toc:
        permalink: ÔÉÅ
    - admonition: {}
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
        extend_pygments_lang:
          - name: php-inline
            lang: php
            options:
                startinline: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
nav:
    - index.md
    - Changes:
        - whatsnew.md
        - for_classic_developers.md
        - devpriorities.md
    - API:
        - api/index.md
        - api/php_api.md
        - api/rest_api.md
        - api/representations.md
        - api/api_reference.md
        - api/rest_api_reference.md
    - Concepts:
        - miscellaneous/acl.md
        - miscellaneous/doctrine_orm.md
        - miscellaneous/forms.md
        - miscellaneous/internationalization.md
    - Configuration:
        - configuration/index.md
        - configuration/config_reference.md
        - configuration/services_and_factories.md
    - Events:
        - events/server_events.md
        - events/client_events.md
        - events/server_event_reference.md
        - events/client_event_reference.md
    - Theme Development:
        - themes/index.md
        - themes/font_icons.md
        - themes/sass_and_css.md
        - themes/style_guide.md
        - themes/theme_functions.md
        - themes/theme_modifications.md
        - themes/theme_settings.md
        - themes/theme_templates.md
        - themes/theme_use_resource_page_blocks.md
    - Module Development:
        - modules/index.md
        - modules/controller_plugins.md
        - modules/data_model.md
        - modules/data_types.md
        - modules/internationalization.md
        - modules/media_ingesters_renderers.md
        - modules/page_blocks.md
        - modules/routes_and_navigation.md
        - modules/view_helpers.md
        - modules/viewmodel.md
    - Modules (Omeka Team):
        - module_docs/Collecting.md
        - module_docs/CopyResources.md
        - module_docs/CustomVocab.md
        - module_docs/Datavis.md
        - module_docs/ExtractMetadata.md
        - module_docs/ExtractText.md
        - module_docs/FacetedBrowse.md
        - module_docs/IiifPresentation.md
        - module_docs/InverseProperties.md
        - module_docs/Mapping.md
        - module_docs/Osii.md
        - module_docs/RedactValues.md
        - module_docs/Scripto.md
        - module_docs/UriDereferencer.md
        - module_docs/ZoteroImport.md
    - Patterns:
        - patterns/index.md
        - patterns/action_list.md
        - patterns/drawer.md
        - patterns/field.md
        - patterns/meta_group.md
    - contributing.md
    - debugging.md
    - register_an_addon.md
